[package]
name = "zerofs"
version = "0.15.2"
edition = "2024"
description = "A high-performance filesystem that makes S3 your primary storage with NFS, 9P, and NBD support"
license = "AGPL-3.0"
repository = "https://github.com/Barre/ZeroFS"
homepage = "https://www.zerofs.net"
documentation = "https://www.zerofs.net"
readme = "../README.md"
keywords = ["filesystem", "s3", "nfs", "distributed", "storage"]
categories = ["filesystem", "network-programming"]

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
strip = true

[profile.ci]
inherits = "release"
lto = false
codegen-units = 16

[dependencies]
slatedb = "0.8.1"
mimalloc = "0.1"
zerofs_nfsserve = "0.14"
tokio = { version = "1.46", features = ["full"] }
async-trait = "0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
object_store = { version = "0.12.3", features = ["aws", "azure", "gcp"] }
bytes = "1.5"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
rand = "0.8"
futures = "0.3"
foyer = "0.17"
foyer-common = "0.17"
chacha20poly1305 = "0.10"
hkdf = "0.12"
sha2 = "0.10"
lz4_flex = "0.11"
anyhow = "1.0"
hex = "0.4"
argon2 = "0.5"
url = "2.5"
deku = "0.19"
thiserror = "2.0"
comfy-table = "7.1"
num-format = "0.4"
libc = "0.2"
dashmap = "6.1"
uuid = { version = "1.17", features = ["v4"] }
toml = "0.9"
shellexpand = "3.1"
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
tempfile = "3.21"
